### ISSUE TITLE
Options Block Extra Whitespace

### ISSUE THREAD

**Issue by allejo** [JeffM2501/UnityBZWTools#1]
![image](https://cloud.githubusercontent.com/assets/1246453/19953740/b3b9f21a-a12e-11e6-9f4c-d8f8c55febf5.png)

Each element from the options block has extra whitespace that comes back even when edited in Unity

**Comment by JeffM2501** [comment]
should be fixed now. I changed how the system trims strings.
if it happens again, attach a sample map to an issue so I can dupe it.

**Comment by allejo** [comment]
It seems like this is still an issue. It happens whenever I use `BZWTools > Save > Save BZW` and the indentation increases by one each time I save

**Comment by JeffM2501** [comment]
Found the issue, fixed
